FROM hub.test.com/builder/python38-base-backend:latest
WORKDIR /backend
COPY ./backend/ .
RUN python3 -m pip install -i https://art-internal.test.com/artifactory/api/pypi/pypi/simple -r requirements.txt
RUN chmod a+x /backend/docker_start.sh
CMD ["/backend/docker_start.sh"]
